
------------------------------------------------------------STORED PROCEDURES FOR INSERT QUERIES------------------------------------------------------


CREATE PROCEDURE INSERT_BANKDATA
AS
    IS_TRUE NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_TRUE FROM BANK;
    
    IF IS_TRUE > 0
    THEN
    DELETE FROM BANK;
    
    INSERT INTO BANK VALUES (111, 'BOSTON UNION BANK', 'INVESTMENT BANK');
    INSERT INTO BANK VALUES (222, 'CITY BANK OF BOSTON', 'THRIFT BANK');
    INSERT INTO BANK VALUES (333, 'BOSTON CAPITAL BANK', 'COMMERCIAL BANK');
    
    ELSE
    INSERT INTO BANK VALUES (111, 'BOSTON UNION BANK', 'INVESTMENT BANK');
    INSERT INTO BANK VALUES (222, 'CITY BANK OF BOSTON', 'THRIFT BANK');
    INSERT INTO BANK VALUES (333, 'BOSTON CAPITAL BANK', 'COMMERCIAL BANK');
    
    END IF;
END;
/

-- BRANCH 

CREATE PROCEDURE INSERT_BRANCHDATA
AS
    IS_TRUE number;
    BANK1 NUMBER;
    BANK2 NUMBER;
    BANK3 NUMBER;

BEGIN
    SELECT COUNT(*) INTO IS_TRUE FROM BRANCH;
    
    IF IS_TRUE > 0
    THEN
    DELETE FROM BRANCH;
    SELECT BANK_CODE INTO BANK1 FROM BANK where BANK_NAME='BOSTON UNION BANK';
    SELECT BANK_CODE INTO BANK2 FROM BANK where BANK_NAME='CITY BANK OF BOSTON';
    SELECT BANK_CODE INTO BANK3 FROM BANK where BANK_NAME='BOSTON CAPITAL BANK';
    
    INSERT INTO BRANCH VALUES (989, 'BU', 'Schiller', 'Boston', 02130, BANK1);
    INSERT INTO BRANCH VALUES (990, 'MU', 'Heath', 'Cambridge', 02016, BANK1);
    INSERT INTO BRANCH VALUES (991, 'KU', 'Minden', 'Brookline', 02245, BANK2);
    INSERT INTO BRANCH VALUES (992, 'TU', 'Parker', 'Somerville', 02367, BANK3);
   
     
    ELSE
    SELECT BANK_CODE INTO BANK1 FROM BANK where BANK_NAME='BOSTON UNION BANK';
    SELECT BANK_CODE INTO BANK2 FROM BANK where BANK_NAME='CITY BANK OF BOSTON';
    SELECT BANK_CODE INTO BANK3 FROM BANK where BANK_NAME='BOSTON CAPITAL BANK';
    
    INSERT INTO BRANCH VALUES (989, 'BU', 'Schiller', 'Boston', 02130, BANK1);
    INSERT INTO BRANCH VALUES (990, 'MU', 'Heath', 'Cambridge', 02016, BANK1);
    INSERT INTO BRANCH VALUES (991, 'KU', 'Minden', 'Brookline', 02245, BANK2);
    INSERT INTO BRANCH VALUES (992, 'TU', 'Parker', 'Somerville', 02367, BANK3);
   
    END IF;
END;
/

--USERS

CREATE PROCEDURE INSERT_USERSDATA
AS
    IS_TRUE number;
    BRANCH1 NUMBER;
    BRANCH2 NUMBER; 
    BRANCH3 NUMBER;
    BRANCH4 NUMBER;
    PERMISSION1 VARCHAR(30);
    PERMISSION2 VARCHAR(30);
    PERMISSION3 VARCHAR(30);
    BEGIN
    SELECT COUNT(*) INTO IS_TRUE FROM USERS;
    
    IF IS_TRUE > 0
    THEN
    DELETE FROM USERS;
    SELECT BRANCH_ID INTO BRANCH1 FROM BRANCH where BRANCH_NAME='BU';
    SELECT BRANCH_ID INTO BRANCH2 FROM BRANCH where BRANCH_NAME='MU';
    SELECT BRANCH_ID INTO BRANCH3 FROM BRANCH where BRANCH_NAME='KU';
    SELECT BRANCH_ID INTO BRANCH4 FROM BRANCH where BRANCH_NAME='TU';
    
    SELECT PERMISSION_ID INTO PERMISSION1 FROM PERMISSION where PERMISSION_TYPE='FULL ACCESS';
    SELECT PERMISSION_ID INTO PERMISSION2 FROM PERMISSION where PERMISSION_TYPE='EXTENDED ACCESS';
    SELECT PERMISSION_ID INTO PERMISSION3 FROM PERMISSION where PERMISSION_TYPE='READONLY ACCESS';
    
     
    INSERT INTO USERS VALUES (32631, 'YES', 'AA1',BRANCH1, PERMISSION1);
    INSERT INTO USERS VALUES (32632, 'NO', 'AA2',BRANCH2, PERMISSION1);
    INSERT INTO USERS VALUES (32633, 'YES', 'AA3',BRANCH3, PERMISSION2);
    INSERT INTO USERS VALUES (32634, 'NO', 'AA4',BRANCH4, PERMISSION3);
    INSERT INTO USERS VALUES (32635, 'YES', 'AA5',BRANCH3, PERMISSION2);
    INSERT INTO USERS VALUES (32636, 'NO', 'AA6',BRANCH4, PERMISSION3);
    INSERT INTO USERS VALUES (32637, 'YES', 'AA7',BRANCH1, PERMISSION3);
    INSERT INTO USERS VALUES (32638, 'YES', 'AA8',BRANCH2, PERMISSION1);
    
    ELSE
    SELECT BRANCH_ID INTO BRANCH1 FROM BRANCH where BRANCH_NAME='BU';
    SELECT BRANCH_ID INTO BRANCH2 FROM BRANCH where BRANCH_NAME='MU';
    SELECT BRANCH_ID INTO BRANCH3 FROM BRANCH where BRANCH_NAME='KU';
    SELECT BRANCH_ID INTO BRANCH4 FROM BRANCH where BRANCH_NAME='TU';
    
    SELECT PERMISSION_ID INTO PERMISSION1 FROM PERMISSION where PERMISSION_TYPE='FULL ACCESS';
    SELECT PERMISSION_ID INTO PERMISSION2 FROM PERMISSION where PERMISSION_TYPE='EXTENDED ACCESS';
    SELECT PERMISSION_ID INTO PERMISSION3 FROM PERMISSION where PERMISSION_TYPE='READONLY ACCESS';
    
     
    INSERT INTO USERS VALUES (32631, 'YES', 'AA1',BRANCH1, PERMISSION1);
    INSERT INTO USERS VALUES (32632, 'NO', 'AA2',BRANCH2, PERMISSION1);
    INSERT INTO USERS VALUES (32633, 'YES', 'AA3',BRANCH3, PERMISSION2);
    INSERT INTO USERS VALUES (32634, 'NO', 'AA4',BRANCH4, PERMISSION3);
    INSERT INTO USERS VALUES (32635, 'YES', 'AA5',BRANCH3, PERMISSION2);
    INSERT INTO USERS VALUES (32636, 'NO', 'AA6',BRANCH4, PERMISSION3);
    INSERT INTO USERS VALUES (32637, 'YES', 'AA7',BRANCH1, PERMISSION3);
    INSERT INTO USERS VALUES (32638, 'YES', 'AA8',BRANCH2, PERMISSION1);
    
    END IF;
END;
/


--ROLES

CREATE PROCEDURE INSERT_ROLESDATA
AS
    is_true number;
    
BEGIN
    SELECT COUNT(*) INTO IS_TRUE FROM ROLES;
    
    IF IS_TRUE > 0
    THEN
    DELETE FROM ROLES;
    INSERT INTO ROLES (ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION) VALUES (13, 'STANDARD', 'NORMAL ACCESS FOR THE USERS');
    INSERT INTO ROLES (ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION) VALUES (14, 'PRIVILAGE', 'SPECIAL ACCESS FOR THE USERS');
    INSERT INTO ROLES (ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION) VALUES (15, 'GUEST', 'READ ONLY ACCESS TO USERS');
   
    ELSE
    INSERT INTO ROLES (ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION) VALUES (13, 'STANDARD', 'NORMAL ACCESS FOR THE USERS');
    INSERT INTO ROLES (ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION) VALUES (14, 'PRIVILAGE', 'SPECIAL ACCESS FOR THE USERS');
    INSERT INTO ROLES (ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION) VALUES (15, 'GUEST', 'READ ONLY ACCESS TO USERS');
   
    END IF;
END;
/
--PERMISSION

CREATE PROCEDURE INSERT_PERMISSIONDATA
AS
    IS_TRUE number;
    ROLEID1 NUMBER;
    ROLEID2 NUMBER;
    ROLEID3 NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_TRUE FROM PERMISSION;
    
    IF IS_TRUE > 0
    THEN
    DELETE FROM PERMISSION;
    SELECT ROLE_ID INTO ROLEID1 FROM ROLES where ROLE_NAME='STANDARD';
    SELECT ROLE_ID INTO ROLEID2 FROM ROLES where ROLE_NAME='PRIVILAGE';
    SELECT ROLE_ID INTO ROLEID3 FROM ROLES where ROLE_NAME='GUEST';
    
    INSERT INTO PERMISSION VALUES (201, 'FULL ACCESS', 'NORMAL ACCESS FOR THE USERS', ROLEID1);
    INSERT INTO PERMISSION VALUES (202, 'EXTENDED ACCESS', 'SPECIAL AND FULL ACCESS FOR THE USERS', ROLEID2);
    INSERT INTO PERMISSION VALUES (203, 'READONLY ACCESS', 'READ ONLY ACCESS TO USERS', ROLEID3);
   
    ELSE
    SELECT ROLE_ID INTO ROLEID1 FROM ROLES where ROLE_NAME='STANDARD';
    SELECT ROLE_ID INTO ROLEID2 FROM ROLES where ROLE_NAME='PRIVILAGE';
    SELECT ROLE_ID INTO ROLEID3 FROM ROLES where ROLE_NAME='GUEST';
    
    INSERT INTO PERMISSION VALUES (201, 'FULL ACCESS', 'NORMAL ACCESS FOR THE USERS', ROLEID1);
    INSERT INTO PERMISSION VALUES (202, 'EXTENDED ACCESS', 'SPECIAL AND FULL ACCESS FOR THE USERS', ROLEID2);
    INSERT INTO PERMISSION VALUES (203, 'READONLY ACCESS', 'READ ONLY ACCESS TO USERS', ROLEID3);
   
    END IF;
END;
/

--EMPLOYEE

CREATE PROCEDURE INSERT_EMPLOYEEDATA
AS
    is_true number;
    
BEGIN
    SELECT COUNT(*) INTO IS_TRUE FROM EMPLOYEE;
    
    IF IS_TRUE > 0
    THEN
    DELETE FROM EMPLOYEE;
    INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_FIRSTNAME, EMPLOYEE_LASTNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHNO, EMPLOYEE_STREET,EMPLOYEE_CITY,EMPLOYEE_ZIPCODE) VALUES (101, 'PATRICK', 'TAYLOR', 'patrik@bostonbank', 6171111111, 'BOYLSTON', 'BOSTON', 02215);
    INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_FIRSTNAME, EMPLOYEE_LASTNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHNO, EMPLOYEE_STREET,EMPLOYEE_CITY,EMPLOYEE_ZIPCODE) VALUES (102, 'CHARLES', 'KENNEDY', 'charles@bostonbank', 6172222222, 'KENMORE', 'BOSTON', 02115);
    INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_FIRSTNAME, EMPLOYEE_LASTNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHNO, EMPLOYEE_STREET,EMPLOYEE_CITY,EMPLOYEE_ZIPCODE) VALUES (103, 'JOHN', 'RAYNOLDS', 'john@bostonbank', 6173333333, 'HUNTINGTON', 'BOSTON', 02245);
    INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_FIRSTNAME, EMPLOYEE_LASTNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHNO, EMPLOYEE_STREET,EMPLOYEE_CITY,EMPLOYEE_ZIPCODE) VALUES (104, 'MYKE', 'SCOTT', 'michael@bostonbank', 6174444444, 'SYMPHONY', 'BOSTON', 02367);

    ELSE
    INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_FIRSTNAME, EMPLOYEE_LASTNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHNO, EMPLOYEE_STREET,EMPLOYEE_CITY,EMPLOYEE_ZIPCODE) VALUES (101, 'PATRICK', 'TAYLOR', 'patrik@bostonbank', 6171111111, 'BOYLSTON', 'BOSTON', 02215);
    INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_FIRSTNAME, EMPLOYEE_LASTNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHNO, EMPLOYEE_STREET,EMPLOYEE_CITY,EMPLOYEE_ZIPCODE) VALUES (102, 'CHARLES', 'KENNEDY', 'charles@bostonbank', 6172222222, 'KENMORE', 'BOSTON', 02115);
    INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_FIRSTNAME, EMPLOYEE_LASTNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHNO, EMPLOYEE_STREET,EMPLOYEE_CITY,EMPLOYEE_ZIPCODE) VALUES (103, 'JOHN', 'RAYNOLDS', 'john@bostonbank', 6173333333, 'HUNTINGTON', 'BOSTON', 02245);
    INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_FIRSTNAME, EMPLOYEE_LASTNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHNO, EMPLOYEE_STREET,EMPLOYEE_CITY,EMPLOYEE_ZIPCODE) VALUES (104, 'MYKE', 'SCOTT', 'michael@bostonbank', 6174444444, 'SYMPHONY', 'BOSTON', 02367);

    END IF;
END;
/

--CUSTOMER

CREATE PROCEDURE INSERT_CUSTOMERDATA
AS
    IS_TRUE number;
    EMPID1 VARCHAR(50);
    EMPID2 VARCHAR(50);
    EMPID3 VARCHAR(50);
    EMPID4 VARCHAR(50);
    USERID1 VARCHAR(50);
    USERID2 VARCHAR(50);
    USERID3 VARCHAR(50);
    USERID4 VARCHAR(50);
    USERID5 VARCHAR(50);
    USERID6 VARCHAR(50);
    USERID7 VARCHAR(50);
    USERID8 VARCHAR(50);
BEGIN
    SELECT COUNT(*) INTO IS_TRUE FROM CUSTOMER;
    
    IF IS_TRUE > 0
    THEN
    DELETE FROM CUSTOMER;
    
    SELECT EMPLOYEE_ID INTO EMPID1 FROM EMPLOYEE where EMPLOYEE_FIRSTNAME='PATRICK';
    SELECT EMPLOYEE_ID INTO EMPID2 FROM EMPLOYEE where EMPLOYEE_FIRSTNAME='CHARLES';
    SELECT EMPLOYEE_ID INTO EMPID3 FROM EMPLOYEE where EMPLOYEE_FIRSTNAME='JOHN';
    SELECT EMPLOYEE_ID INTO EMPID4 FROM EMPLOYEE where EMPLOYEE_FIRSTNAME='MYKE';
    
    SELECT USER_ID INTO USERID1 FROM USERS where USER_UNIQUE_CHARACTER='AA1';
    SELECT USER_ID INTO USERID2 FROM USERS where USER_UNIQUE_CHARACTER='AA2';
    SELECT USER_ID INTO USERID3 FROM USERS where USER_UNIQUE_CHARACTER='AA3';
    SELECT USER_ID INTO USERID4 FROM USERS where USER_UNIQUE_CHARACTER='AA4';
    SELECT USER_ID INTO USERID5 FROM USERS where USER_UNIQUE_CHARACTER='AA5';
    SELECT USER_ID INTO USERID6 FROM USERS where USER_UNIQUE_CHARACTER='AA6';
    SELECT USER_ID INTO USERID7 FROM USERS where USER_UNIQUE_CHARACTER='AA7';
    SELECT USER_ID INTO USERID8 FROM USERS where USER_UNIQUE_CHARACTER='AA8';
    
    
    INSERT INTO CUSTOMER VALUES ('SAK05', 'SAKSHI', 'PEKALE', 1122111111,'BOYLSTON', 'BOSTON',02215, EMPID1, USERID1);
    INSERT INTO CUSTOMER VALUES ('KUN23', 'KUNAL', 'THAPA', 2222233333,'SCHILLER', 'BOSTON',02315, EMPID2, USERID2);
    INSERT INTO CUSTOMER VALUES ('SHUB01', 'SHUBHAM', 'IDEKAR', 4444433333,'HUNTINGTON', 'BOSTON',02115, EMPID3, USERID3);
    INSERT INTO CUSTOMER VALUES ('TAN02', 'TANVI', 'VALKUNDE', 5555544444,'BROOKLINE', 'BOSTON',03110, EMPID4, USERID4);
    INSERT INTO CUSTOMER VALUES ('SAY22', 'SAYALI', 'HULLE', 6666655555,'BOYLSTON', 'BOSTON',02215, EMPID1, USERID5);
    INSERT INTO CUSTOMER VALUES ('SAKS20', 'SAKSHEE', 'SASALATE', 7777766666,'BOYLSTON', 'BOSTON',02215, EMPID2, USERID6);
    INSERT INTO CUSTOMER VALUES ('UDD18', 'UDDHAV', 'ZAMBARE', 8888877777,'PARKDRIVE', 'BOSTON',02315, EMPID3, USERID7);
    INSERT INTO CUSTOMER VALUES ('SID30', 'SIDDHESH', 'DHAVALE', 9999988888,'JVUE', 'BOSTON',02115, EMPID4, USERID8);
    
    ELSE
    SELECT EMPLOYEE_ID INTO EMPID1 FROM EMPLOYEE where EMPLOYEE_FIRSTNAME='PATRICK';
    SELECT EMPLOYEE_ID INTO EMPID2 FROM EMPLOYEE where EMPLOYEE_FIRSTNAME='CHARLES';
    SELECT EMPLOYEE_ID INTO EMPID3 FROM EMPLOYEE where EMPLOYEE_FIRSTNAME='JOHN';
    SELECT EMPLOYEE_ID INTO EMPID4 FROM EMPLOYEE where EMPLOYEE_FIRSTNAME='MYKE';
    
    SELECT USER_ID INTO USERID1 FROM USERS where USER_UNIQUE_CHARACTER='AA1';
    SELECT USER_ID INTO USERID2 FROM USERS where USER_UNIQUE_CHARACTER='AA2';
    SELECT USER_ID INTO USERID3 FROM USERS where USER_UNIQUE_CHARACTER='AA3';
    SELECT USER_ID INTO USERID4 FROM USERS where USER_UNIQUE_CHARACTER='AA4';
    SELECT USER_ID INTO USERID5 FROM USERS where USER_UNIQUE_CHARACTER='AA5';
    SELECT USER_ID INTO USERID6 FROM USERS where USER_UNIQUE_CHARACTER='AA6';
    SELECT USER_ID INTO USERID7 FROM USERS where USER_UNIQUE_CHARACTER='AA7';
    SELECT USER_ID INTO USERID8 FROM USERS where USER_UNIQUE_CHARACTER='AA8';
    
    INSERT INTO CUSTOMER VALUES ('SAK05', 'SAKSHI', 'PEKALE', 1122111111,'BOYLSTON', 'BOSTON',02215, EMPID1, USERID1);
    INSERT INTO CUSTOMER VALUES ('KUN23', 'KUNAL', 'THAPA', 2222233333,'SCHILLER', 'BOSTON',02315, EMPID2, USERID2);
    INSERT INTO CUSTOMER VALUES ('SHUB01', 'SHUBHAM', 'IDEKAR', 4444433333,'HUNTINGTON', 'BOSTON',02115, EMPID3, USERID3);
    INSERT INTO CUSTOMER VALUES ('TAN02', 'TANVI', 'VALKUNDE', 5555544444,'BROOKLINE', 'BOSTON',03110, EMPID4, USERID4);
    INSERT INTO CUSTOMER VALUES ('SAY22', 'SAYALI', 'HULLE', 6666655555,'BOYLSTON', 'BOSTON',02215, EMPID1, USERID5);
    INSERT INTO CUSTOMER VALUES ('SAKS20', 'SAKSHEE', 'SASALATE', 7777766666,'BOYLSTON', 'BOSTON',02215, EMPID2, USERID6);
    INSERT INTO CUSTOMER VALUES ('UDD18', 'UDDHAV', 'ZAMBARE', 8888877777,'PARKDRIVE', 'BOSTON',02315, EMPID3, USERID7);
    INSERT INTO CUSTOMER VALUES ('SID30', 'SIDDHESH', 'DHAVALE', 9999988888,'JVUE', 'BOSTON',02115, EMPID4, USERID8);
    
    
    END IF;
END;
/

--ACCOUNTS

CREATE PROCEDURE INSERT_ACCOUNTSDATA
AS
    IS_TRUE number;
    customer1 VARCHAR(50);
    customer2 VARCHAR(50);
    customer3 VARCHAR(50);
    customer4 VARCHAR(50);
    customer5 VARCHAR(50);
    customer6 VARCHAR(50);
    customer7 VARCHAR(50);
    customer8 VARCHAR(50);
BEGIN
    SELECT COUNT(*) INTO IS_TRUE FROM ACCOUNTS;
    
    IF IS_TRUE > 0
    THEN
    DELETE FROM ACCOUNTS;
    SELECT CUSTOMER_ID INTO customer1 FROM CUSTOMER where CUSTOMER_FIRSTNAME='SAKSHI';
    SELECT CUSTOMER_ID INTO customer2 FROM CUSTOMER where CUSTOMER_FIRSTNAME='KUNAL';
    SELECT CUSTOMER_ID INTO customer3 FROM CUSTOMER where CUSTOMER_FIRSTNAME='SHUBHAM';
    SELECT CUSTOMER_ID INTO customer4 FROM CUSTOMER where CUSTOMER_FIRSTNAME='TANVI';
    SELECT CUSTOMER_ID INTO customer5 FROM CUSTOMER where CUSTOMER_FIRSTNAME='SAYALI';
    SELECT CUSTOMER_ID INTO customer6 FROM CUSTOMER where CUSTOMER_FIRSTNAME='SAKSHEE';
    SELECT CUSTOMER_ID INTO customer7 FROM CUSTOMER where CUSTOMER_FIRSTNAME='UDDHAV';
    SELECT CUSTOMER_ID INTO customer8 FROM CUSTOMER where CUSTOMER_FIRSTNAME='SIDDHESH';
    
    INSERT INTO ACCOUNTS VALUES (12345678, 'SAVINGS', 46007.232, '05-JAN-2010', customer1);
    INSERT INTO ACCOUNTS VALUES (87654321, 'SAVINGS', 56766.02, '12-MAY-2018',customer2);
    INSERT INTO ACCOUNTS VALUES (11111111, 'CURRENTS', 892.12, '23-FEB-1997',customer3);
    INSERT INTO ACCOUNTS VALUES (22222222, 'SAVINGS', 2132.99, '17-DEC-2014',customer4);
    INSERT INTO ACCOUNTS VALUES (21537625, 'SAVINGS', 46007.232, '05-JAN-2010', customer5);
    INSERT INTO ACCOUNTS VALUES (79870076, 'SAVINGS', 56766.02, '12-MAY-2018',customer6);
    INSERT INTO ACCOUNTS VALUES (23402047, 'CURRENTS', 892.12, '23-FEB-1997',customer7);
    INSERT INTO ACCOUNTS VALUES (79239420, 'SAVINGS', 2132.99, '17-DEC-2014',customer8);


    
    ELSE
    SELECT CUSTOMER_ID INTO customer1 FROM CUSTOMER where CUSTOMER_FIRSTNAME='SAKSHI';
    SELECT CUSTOMER_ID INTO customer2 FROM CUSTOMER where CUSTOMER_FIRSTNAME='KUNAL';
    SELECT CUSTOMER_ID INTO customer3 FROM CUSTOMER where CUSTOMER_FIRSTNAME='SHUBHAM';
    SELECT CUSTOMER_ID INTO customer4 FROM CUSTOMER where CUSTOMER_FIRSTNAME='TANVI';
    SELECT CUSTOMER_ID INTO customer5 FROM CUSTOMER where CUSTOMER_FIRSTNAME='SAYALI';
    SELECT CUSTOMER_ID INTO customer6 FROM CUSTOMER where CUSTOMER_FIRSTNAME='SAKSHEE';
    SELECT CUSTOMER_ID INTO customer7 FROM CUSTOMER where CUSTOMER_FIRSTNAME='UDDHAV';
    SELECT CUSTOMER_ID INTO customer8 FROM CUSTOMER where CUSTOMER_FIRSTNAME='SIDDHESH';
    
    INSERT INTO ACCOUNTS VALUES (12345678, 'SAVINGS', 46007.232, '05-JAN-2010', customer1);
    INSERT INTO ACCOUNTS VALUES (87654321, 'SAVINGS', 56766.02, '12-MAY-2018',customer2);
    INSERT INTO ACCOUNTS VALUES (11111111, 'CURRENTS', 892.12, '23-FEB-1997',customer3);
    INSERT INTO ACCOUNTS VALUES (22222222, 'SAVINGS', 2132.99, '17-DEC-2014',customer4);
    INSERT INTO ACCOUNTS VALUES (21537625, 'SAVINGS', 46007.232, '05-JAN-2010', customer5);
    INSERT INTO ACCOUNTS VALUES (79870076, 'SAVINGS', 56766.02, '12-MAY-2018',customer6);
    INSERT INTO ACCOUNTS VALUES (23402047, 'CURRENTS', 892.12, '23-FEB-1997',customer7);
    INSERT INTO ACCOUNTS VALUES (79239420, 'SAVINGS', 2132.99, '17-DEC-2014',customer8);


    END IF;
END;
/

--TRANSACTION

CREATE PROCEDURE INSERT_TRANSACTIONDATA
AS
    IS_TRUE number;
    ACCOUNT1 NUMBER;
    ACCOUNT2 NUMBER;
    ACCOUNT3 NUMBER;
    ACCOUNT4 NUMBER;
    ACCOUNT5 NUMBER;
    ACCOUNT6 NUMBER;
    ACCOUNT7 NUMBER;
    ACCOUNT8 NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_TRUE FROM TRANSACTION;
    
    IF IS_TRUE > 0
    THEN
    DELETE FROM TRANSACTION;
    SELECT ACCOUNT_NO INTO ACCOUNT1 FROM ACCOUNTS where FK_CUSTOMER_ID='SAK05';
    SELECT ACCOUNT_NO INTO ACCOUNT2 FROM ACCOUNTS where FK_CUSTOMER_ID='KUN23';
    SELECT ACCOUNT_NO INTO ACCOUNT3 FROM ACCOUNTS where FK_CUSTOMER_ID='SHUB01';
    SELECT ACCOUNT_NO INTO ACCOUNT4 FROM ACCOUNTS where FK_CUSTOMER_ID='TAN02';
    SELECT ACCOUNT_NO INTO ACCOUNT5 FROM ACCOUNTS where FK_CUSTOMER_ID='SAY22';
    SELECT ACCOUNT_NO INTO ACCOUNT6 FROM ACCOUNTS where FK_CUSTOMER_ID='SAKS20';
    SELECT ACCOUNT_NO INTO ACCOUNT7 FROM ACCOUNTS where FK_CUSTOMER_ID='UDD18';
    SELECT ACCOUNT_NO INTO ACCOUNT8 FROM ACCOUNTS where FK_CUSTOMER_ID='SID30';
    INSERT INTO TRANSACTION VALUES (9831, 100000,'FEES PAYMENT', '05-FEB-2022', 'Debit', ACCOUNT1, ACCOUNT2);
    INSERT INTO TRANSACTION VALUES (9832, 250,'GROCERY', '01-MAY-2022', 'Debit',ACCOUNT2, ACCOUNT3);
    INSERT INTO TRANSACTION VALUES (9833, 4000000,'FEES PAYMENT', '10-JAN-2022', 'Credit', ACCOUNT4, ACCOUNT1);
    INSERT INTO TRANSACTION VALUES (9834, 700000,'FEES PAYMENT', '05-FEB-2022', 'Debit', ACCOUNT5, ACCOUNT8);
    INSERT INTO TRANSACTION VALUES (9835, 5000,'RENT', '01-MAY-2022', 'Debit',ACCOUNT6, ACCOUNT7);
    INSERT INTO TRANSACTION VALUES (9836, 40,'ELECTRICITY BILL', '10-JAN-2022', 'Credit', ACCOUNT7, ACCOUNT5);
    INSERT INTO TRANSACTION VALUES (9837, 1000,'SHOPPING', '05-FEB-2022', 'Debit', ACCOUNT3, ACCOUNT6);
    INSERT INTO TRANSACTION VALUES (9838, 2500,'RENT', '01-MAY-2022', 'Debit',ACCOUNT8, ACCOUNT4);
    
    ELSE
    SELECT ACCOUNT_NO INTO ACCOUNT1 FROM ACCOUNTS where FK_CUSTOMER_ID='SAK05';
    SELECT ACCOUNT_NO INTO ACCOUNT2 FROM ACCOUNTS where FK_CUSTOMER_ID='KUN23';
    SELECT ACCOUNT_NO INTO ACCOUNT3 FROM ACCOUNTS where FK_CUSTOMER_ID='SHUB01';
    SELECT ACCOUNT_NO INTO ACCOUNT4 FROM ACCOUNTS where FK_CUSTOMER_ID='TAN02';
    SELECT ACCOUNT_NO INTO ACCOUNT5 FROM ACCOUNTS where FK_CUSTOMER_ID='SAY22';
    SELECT ACCOUNT_NO INTO ACCOUNT6 FROM ACCOUNTS where FK_CUSTOMER_ID='SAKS20';
    SELECT ACCOUNT_NO INTO ACCOUNT7 FROM ACCOUNTS where FK_CUSTOMER_ID='UDD18';
    SELECT ACCOUNT_NO INTO ACCOUNT8 FROM ACCOUNTS where FK_CUSTOMER_ID='SID30';
    INSERT INTO TRANSACTION VALUES (9831, 10000,'FEES PAYMENT', '05-FEB-2022', 'Debit', ACCOUNT1, ACCOUNT2);
    INSERT INTO TRANSACTION VALUES (9832, 250,'GROCERY', '01-MAY-2022', 'Debit',ACCOUNT2, ACCOUNT3);
    INSERT INTO TRANSACTION VALUES (9833, 40000,'FEES PAYMENT', '10-JAN-2022', 'Credit', ACCOUNT4, ACCOUNT1);
    INSERT INTO TRANSACTION VALUES (9834, 70000,'FEES PAYMENT', '05-FEB-2022', 'Debit', ACCOUNT5, ACCOUNT8);
    INSERT INTO TRANSACTION VALUES (9835, 5000,'RENT', '01-MAY-2022', 'Debit',ACCOUNT6, ACCOUNT7);
    INSERT INTO TRANSACTION VALUES (9836, 40,'ELECTRICITY BILL', '10-JAN-2022', 'Credit', ACCOUNT7, ACCOUNT5);
    INSERT INTO TRANSACTION VALUES (9837, 1000,'SHOPPING', '05-FEB-2022', 'Debit', ACCOUNT3, ACCOUNT6);
    INSERT INTO TRANSACTION VALUES (9838, 2500,'RENT', '01-MAY-2022', 'Debit',ACCOUNT8, ACCOUNT4);
       
    
    END IF;
END;
/

--LOAN

CREATE PROCEDURE INSERT_LOANDATA
AS
    IS_TRUE number;
    ACCOUNT1 NUMBER;
    ACCOUNT2 NUMBER;
    ACCOUNT3 NUMBER;
    ACCOUNT4 NUMBER;
    ACCOUNT5 NUMBER;
    ACCOUNT6 NUMBER;
    ACCOUNT7 NUMBER;
    ACCOUNT8 NUMBER;

BEGIN
    SELECT COUNT(*) INTO IS_TRUE FROM LOAN;
    
    IF IS_TRUE > 0
    THEN
    DELETE FROM LOAN;
    SELECT ACCOUNT_NO INTO ACCOUNT1 FROM ACCOUNTS where FK_CUSTOMER_ID='SAK05';
    SELECT ACCOUNT_NO INTO ACCOUNT2 FROM ACCOUNTS where FK_CUSTOMER_ID='KUN23';
    SELECT ACCOUNT_NO INTO ACCOUNT3 FROM ACCOUNTS where FK_CUSTOMER_ID='SHUB01';
    SELECT ACCOUNT_NO INTO ACCOUNT4 FROM ACCOUNTS where FK_CUSTOMER_ID='TAN02';
    SELECT ACCOUNT_NO INTO ACCOUNT5 FROM ACCOUNTS where FK_CUSTOMER_ID='SAY22';
    SELECT ACCOUNT_NO INTO ACCOUNT6 FROM ACCOUNTS where FK_CUSTOMER_ID='SAKS20';
    SELECT ACCOUNT_NO INTO ACCOUNT7 FROM ACCOUNTS where FK_CUSTOMER_ID='UDD18';
    SELECT ACCOUNT_NO INTO ACCOUNT8 FROM ACCOUNTS where FK_CUSTOMER_ID='SID30';
    INSERT INTO loan VALUES ('X32', 86000, 'COLLATERAL', '24 MONTHS','07-FEB-2015',ACCOUNT1);
    INSERT INTO LOAN VALUES ('Y56', 90000, 'NON-COLLATERAL', '96 MONTHS','11-MAY-2019',ACCOUNT7);
    INSERT INTO LOAN VALUES ('S121', 432000, 'NON-COLLATERAL', '54 MONTHS','09-JUN-2009',ACCOUNT8);
    INSERT INTO LOAN VALUES ('U7564', 34567, 'COLLATERAL', '36 MONTHS','05-MAR-2022',ACCOUNT8);
    INSERT INTO loan VALUES ('X321', 86010, 'COLLATERAL', '24 MONTHS','07-DEC-2015',ACCOUNT6);
    INSERT INTO LOAN VALUES ('Y564', 90230, 'NON-COLLATERAL', '96 MONTHS','11-FEB-2019',ACCOUNT1);
    INSERT INTO LOAN VALUES ('6121', 432560, 'NON-COLLATERAL', '54 MONTHS','09-AUG-2009',ACCOUNT7);
    INSERT INTO LOAN VALUES ('U75Y4', 34587, 'COLLATERAL', '36 MONTHS','05-MAY-2022',ACCOUNT2);

    ELSE
    SELECT ACCOUNT_NO INTO ACCOUNT1 FROM ACCOUNTS where FK_CUSTOMER_ID='SAK05';
    SELECT ACCOUNT_NO INTO ACCOUNT2 FROM ACCOUNTS where FK_CUSTOMER_ID='KUN23';
    SELECT ACCOUNT_NO INTO ACCOUNT3 FROM ACCOUNTS where FK_CUSTOMER_ID='SHUB01';
    SELECT ACCOUNT_NO INTO ACCOUNT4 FROM ACCOUNTS where FK_CUSTOMER_ID='TAN02';
    SELECT ACCOUNT_NO INTO ACCOUNT5 FROM ACCOUNTS where FK_CUSTOMER_ID='SAY22';
    SELECT ACCOUNT_NO INTO ACCOUNT6 FROM ACCOUNTS where FK_CUSTOMER_ID='SAKS20';
    SELECT ACCOUNT_NO INTO ACCOUNT7 FROM ACCOUNTS where FK_CUSTOMER_ID='UDD18';
    SELECT ACCOUNT_NO INTO ACCOUNT8 FROM ACCOUNTS where FK_CUSTOMER_ID='SID30';
    INSERT INTO loan VALUES ('X32', 86000, 'COLLATERAL', '24 MONTHS','07-FEB-2015',ACCOUNT1);
    INSERT INTO LOAN VALUES ('Y56', 90000, 'NON-COLLATERAL', '96 MONTHS','11-MAY-2019',ACCOUNT7);
    INSERT INTO LOAN VALUES ('S121', 432000, 'NON-COLLATERAL', '54 MONTHS','09-JUN-2009',ACCOUNT8);
    INSERT INTO LOAN VALUES ('U7564', 34567, 'COLLATERAL', '36 MONTHS','05-MAR-2022',ACCOUNT3);
    INSERT INTO LOAN VALUES ('X321', 86010, 'COLLATERAL', '24 MONTHS','07-DEC-2015',ACCOUNT6);
    INSERT INTO LOAN VALUES ('Y564', 90230, 'NON-COLLATERAL', '96 MONTHS','11-FEB-2019',ACCOUNT1);
    INSERT INTO LOAN VALUES ('6121', 432560, 'NON-COLLATERAL', '54 MONTHS','09-AUG-2009',ACCOUNT7);
    INSERT INTO LOAN VALUES ('U75Y4', 34587, 'COLLATERAL', '36 MONTHS','05-MAY-2022',ACCOUNT2);

    
    END IF;
END;
/

EXEC INSERT_BANKDATA;
EXEC INSERT_BRANCHDATA;
EXEC INSERT_ROLESDATA;
EXEC INSERT_EMPLOYEEDATA;
EXEC INSERT_PERMISSIONDATA;
EXEC INSERT_USERSDATA;
EXEC INSERT_CUSTOMERDATA;
EXEC INSERT_ACCOUNTSDATA;
EXEC INSERT_TRANSACTIONDATA;
EXEC INSERT_LOANDATA;